export enum UserException {
	EMAIL_EXISTED = 'EMAIL_EXISTED',

	OLD_PASSWORD_INCORRECT = 'OLD_PASSWORD_INCORRECT',

	USERNAME_TAKEN = 'USERNAME_TAKEN',

	USERNAME_REQUIRED = 'USERNAME_REQUIRE',

	USER_NOT_EXISTED = 'USER_NOT_EXISTED',
}
